### ISSUE TITLE
Auto indent file

### ISSUE THREAD

**Issue by sonbui00** [joom/vim-starter#2]
I have some problems with git when the files open, they will be auto indent, So more lines will be changed in git. I don't want commit many lines. Please help me.

**Comment by joom** [comment]
You can delete certain lines in your `vimrc` file, you might want to look at [these lines especially](https://github.com/joom/vim-starter/blob/b36c735baf2229a69c3832407d726f595c5f8939/vimrc#L107-L131). Let me know if that helps.

**Comment by sonbui00** [comment]
thanks for your help. it seem better.
